name: Deploy to Dev - EU Region

on:
  pull_request:
    branches:
      - dev

jobs:
  deploy-dev-eu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Deploy to Dev - EU
        run: |
          echo "Deploying to Dev EU Region with Image Tag: ${{ secrets.DEV_EU_IMAGE_TAG }}"
