name: Deploy to Dev - US Region

on:
  pull_request:
    branches:
      - dev

jobs:
  deploy-dev-us:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract image tag for Dev US
        run: |
          PR_BODY=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }})
          
          IMAGE_TAG_DEV_US=$(echo "$PR_BODY" | grep -oP '(?<=Dev: )[^\n]+' | xargs)
          echo "Dev US Image Tag: $IMAGE_TAG_DEV_US"
          echo "IMAGE_TAG_DEV_US=$IMAGE_TAG_DEV_US" >> $GITHUB_ENV

      - name: Deploy to Dev - US
        run: |
          echo "Deploying to Dev US Region with Image Tag: $IMAGE_TAG_DEV_US"
          # Add your deployment command here, e.g., kubectl, docker, etc.
