name: Dev-EU Deployment

on:
  pull_request:
    branches:
      - dev

jobs:
  deploy-dev-eu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract PR Details
        run: |
          echo "Extracting PR details for Dev-EU..."
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")

          # Check if Dev is selected
          DEV_SELECTED=$(echo "$PR_BODY" | grep -i "Dev: \`Y\`" || echo "")
          if [[ -z "$DEV_SELECTED" ]]; then
            echo "Dev environment not selected for deployment. Skipping..."
            exit 0
          fi

          # Extract EU tag
          EU_TAG=$(echo "$PR_BODY" | sed -n 's/.*\*\*EU Region:\*\* `\([^`]*\)`/\1/p')
          if [[ -z "$EU_TAG" ]]; then
            echo "EU tag not provided for Dev. Exiting..."
            exit 1
          fi

          echo "EU_TAG=$EU_TAG" >> $GITHUB_ENV
          echo "Extracted EU tag: $EU_TAG"

      - name: Deploy to Dev EU
        run: |
          echo "Deploying Dev EU Region..."
          echo "Using EU Tag: $EU_TAG"
