name: Dev-US Deployment

on:
  pull_request:
    branches:
      - dev


jobs:
  deploy-dev-us:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract PR Details
        run: |
          echo "Extracting PR details for Dev-US..."
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")

          # Check if Dev is selected
          DEV_SELECTED=$(echo "$PR_BODY" | grep -i "Dev: \`Y\`" || echo "")
          if [[ -z "$DEV_SELECTED" ]]; then
            echo "Dev environment not selected for deployment. Skipping..."
            exit 0
          fi

          # Extract US tag
          US_TAG=$(echo "$PR_BODY" | sed -n 's/.*\*\*US Region:\*\* `\([^`]*\)`/\1/p')

          if [[ -z "$US_TAG" ]]; then
            echo "US tag not provided for Dev. Exiting..."
            exit 1
          fi

          echo "US_TAG=$US_TAG" >> $GITHUB_ENV
          echo "Extracted US tag: $US_TAG"

      - name: Deploy to Dev US
        run: |
          echo "Deploying Dev US Region..."
          echo "Using US Tag: $US_TAG"
