name: Dev-AP Deployment

on:
  pull_request:
    branches:
      - dev

jobs:
  deploy-dev-ap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract PR Details
        run: |
          echo "Extracting PR details for Dev-AP..."
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")

          # Check if Dev is selected
          DEV_SELECTED=$(echo "$PR_BODY" | grep -i "Dev: \`Y\`" || echo "")
          if [[ -z "$DEV_SELECTED" ]]; then
            echo "Dev environment not selected for deployment. Skipping..."
            exit 0
          fi

          # Extract AP tag using sed
          AP_TAG=$(echo "$PR_BODY" | sed -n 's/.*\*\*AP Region:\*\* `\([^`]*\)`/\1/p')
          if [[ -z "$AP_TAG" ]]; then
            echo "AP tag not provided for Dev. Exiting..."
            exit 1
          fi

          echo "AP_TAG=$AP_TAG" >> $GITHUB
