name: Preprod-EU Deployment

on:
  pull_request:
    branches:
      - preprod

jobs:
  deploy-preprod-eu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract PR Details
        run: |
          echo "Extracting PR details for Preprod-EU..."
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")

          # Check if Preprod is selected
          PREPROD_SELECTED=$(echo "$PR_BODY" | grep -i "Preprod: \`Y\`" || echo "")
          if [[ -z "$PREPROD_SELECTED" ]]; then
            echo "Preprod environment not selected for deployment. Skipping..."
            exit 0
          fi

          # Extract EU tag
          EU_TAG=$(echo "$PR_BODY" | grep -oP '(?<=### Preprod Environment\s+- \*\*EU Region:\*\* `)[^`]+')
          if [[ -z "$EU_TAG" ]]; then
            echo "EU tag not provided for Preprod. Exiting..."
            exit 1
          fi

          echo "EU_TAG=$EU_TAG" >> $GITHUB_ENV
          echo "Extracted EU tag: $EU_TAG"

      - name: Deploy to Preprod EU
        run: |
          echo "Deploying Preprod EU Region..."
          echo "Using EU Tag: $EU_TAG"
