name: Preprod-US Deployment

on:
  pull_request:
    branches:
      - preprod  # Only trigger on PRs targeting the 'preprod' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Parse PR Body
        id: parse_pr
        run: |
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")
          echo "PR_BODY=$PR_BODY"

          PREPROD_SELECTED=$(echo "$PR_BODY" |
