name: Preprod-AP Deployment

on:
  pull_request:
    branches:
      - preprod  # Only trigger on PRs targeting the 'preprod' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Parse PR Body
        id: parse_pr
        run: |
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")
          echo "PR_BODY=$PR_BODY"

          PREPROD_SELECTED=$(echo "$PR_BODY" | grep -oP '(?<=- Preprod: `)[^`]+')
          PREPROD_IMAGE_AP=$(echo "$PR_BODY" | grep -A 3 "Preprod Environment" | grep "AP Region:" | awk -F'`' '{print $2}' | tr -d '[:space:]')

          echo "PREPROD_SELECTED=$PREPROD_SELECTED" >> $GITHUB_ENV
          echo "PREPROD_IMAGE_AP=$PREPROD_IMAGE_AP" >> $GITHUB_ENV

      - name: Validate and Deploy Preprod-AP
        run: |
          if [ "$PREPROD_SELECTED" == "Y" ]; then
            if [ -z "$PREPROD_IMAGE_AP" ]; then
              echo "Error: Missing image tag value for Preprod-AP."
              exit 1
            fi
            echo "Deploying Preprod-AP with image tag: $PREPROD_IMAGE_AP"
          else
            echo "Preprod environment is not selected for deployment."
            exit 0
          fi
