name: Preprod - AP Region

on:
  pull_request:
    types: [opened, edited, reopened]
    paths:
      - .github/workflows/preprod-ap.yaml

jobs:
  deploy-preprod-ap:
    if: >
      github.event.pull_request.title contains 'ap' &&
      github.event.pull_request.title contains 'eu' &&
      github.event.pull_request.title contains 'us' &&
      github.event.pull_request.title contains 'rG'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Pre prod AP Deployment
        run: |
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")
          PREPROD_SELECTED=$(echo "$PR_BODY" | grep -oP '(?<=- Preprod: `)[^`]+')

          if [ "$PREPROD_SELECTED" != "Y" ]; then
            echo "Preprod environment not selected for deployment. Skipping."
            exit 0
          fi

          PREPROD_IMAGE_AP=$(echo "$PR_BODY" | grep -A 3 "Preprod Environment" | grep "AP Region:" | awk -F'`' '{print $2}' | tr -d '[:space:]')
          if [ -z "$PREPROD_IMAGE_AP" ]; then
            echo "Error: Missing image tag for Preprod AP Region."
            exit 1
          fi

          echo "Deploying Preprod - AP Region with image tag: $PREPROD_IMAGE_AP"
