name: Preprod-AP Deployment

on:
  pull_request:
    branches:
      - preprod

jobs:
  deploy-preprod-ap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract PR Details
        run: |
          echo "Extracting PR details for Preprod-AP..."
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")

          # Check if Preprod is selected
          PREPROD_SELECTED=$(echo "$PR_BODY" | grep -i "Preprod: \`Y\`" || echo "")
          if [[ -z "$PREPROD_SELECTED" ]]; then
            echo "Preprod environment not selected for deployment. Skipping..."
            exit 0
          fi

          # Extract AP tag using sed
          AP_TAG=$(echo "$PR_BODY" | sed -n 's/.*\*\*AP Region:\*\* `\([^`]*\)`/\1/p')
          if [[ -z "$AP_TAG" ]]; then
            echo "AP tag not provided for Preprod. Exiting..."
            exit 1
          fi

          echo "AP_TAG=$AP_TAG" >> $GITHUB_ENV
          echo "Extracted AP tag: $AP_TAG"

      - name: Deploy to Preprod AP
        run: |
          echo "Deploying Preprod AP Region..."
          echo "Using AP Tag: $AP_TAG"
