name: Deploy to Preprod - EU Region

on:
  pull_request:
    branches:
      - preprod

jobs:
  deploy-preprod-eu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Deploy to Preprod - EU
        run: |
          echo "Deploying to Preprod EU  Region with Image Tag: ${{ secrets.PREPROD_EU_IMAGE_TAG }}"
