name: Deploy to Preprod - US Region

on:
  pull_request:
    branches:
      - preprod

jobs:
  deploy-preprod-us:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Deploy to Preprod - US
        run: |
          echo "Deploying to Preprod US Region with Image Tag: ${{ secrets.PREPROD_US_IMAGE_TAG }}"
