name: Prod-AP Deployment

on:
  pull_request:
    branches:
      - prod

jobs:
  deploy-prod-ap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract PR Details
        run: |
          echo "Extracting PR details for Prod-AP..."
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")

          # Check if Prod is selected
          PROD_SELECTED=$(echo "$PR_BODY" | grep -i "Prod: \`Y\`" || echo "")
          if [[ -z "$PROD_SELECTED" ]]; then
            echo "Prod environment not selected for deployment. Skipping..."
            exit 0
          fi

          # Extract AP tag using sed (avoiding lookbehind issues)
          AP_TAG=$(echo "$PR_BODY" | sed -n 's/.*\*\*AP Region:\*\* `\([^`]*\)`/\1/p')
          if [[ -z "$AP_TAG" ]]; then
            echo "AP tag not provided for Prod. Exiting..."
            exit 1
          fi

          echo "AP_TAG=$AP_TAG" >> $GITHUB_ENV
          echo "Extracted AP tag: $AP_TAG"

      - name: Deploy to Prod AP
        run: |
          echo "Deploying Prod AP Region..."
          echo "Using AP Tag: $AP_TAG"
