name: Prod-AP Deployment

on:
  pull_request:
    branches:
      - prod  # Trigger only for PRs targeting 'prod' branch

jobs:
  deploy-ap:
    if: contains(github.event.pull_request.title, '[ap]')  # Trigger only if PR title contains '[ap]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Prod-AP
        run: |
          echo "Deploying Prod-AP region..."
          # Add your deployment commands for Prod-AP here
