name: Prod-EU Deployment

on:
  pull_request:
    branches:
      - prod  # Trigger only for PRs targeting 'prod' branch

jobs:
  deploy-eu:
    if: contains(github.event.pull_request.title, '[eu]')  # Trigger only if PR title contains '[eu]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Image Tag Values
        id: extract-tags
        run: |
          echo "Extracting image tags for Prod-EU..."
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")

          EU_TAG=$(echo "$PR_BODY" | grep -oP '(?<=### Prod Environment\s+- \*\*EU Region:\*\* `)[^`]+')

          echo "EU_TAG=$EU_TAG" >> $GITHUB_ENV
          echo "Extracted EU tag: $EU_TAG"

      - name: Deploy Prod-EU
        run: |
          echo "Deploying Prod-EU region..."
          echo "Using image tag: $EU_TAG"
