name: Deploy to Prod - US Region

on:
  pull_request:
    branches:
      - prod

jobs:
  deploy-prod-us:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract image tag for Prod US
        run: |
          PR_BODY=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }})
          
          IMAGE_TAG_PROD_US=$(echo "$PR_BODY" | grep -oP '(?<=Prod: )[^\n]+' | xargs)
          echo "Prod US Image Tag: $IMAGE_TAG_PROD_US"
          echo "IMAGE_TAG_PROD_US=$IMAGE_TAG_PROD_US" >> $GITHUB_ENV

      - name: Deploy to Prod - US
        run: |
          echo "Deploying to Prod US Region with Image Tag: $IMAGE_TAG_PROD_US"
          # Add your deployment command here
