
name: Prod-us Deployment

on:
  pull_request:
    branches:
      - prod  # Trigger only for PRs targeting the 'prod' branch


jobs:
  deploy-us:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check if us Deployment is Required
        id: check-us
        run: |
          echo "Parsing PR title for us region..."
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR Title: $PR_TITLE"

          if [[ "$PR_TITLE" == *"[us]"* || "$PR_TITLE" == *"[ap ,eu,us]"* || "$PR_TITLE" == *"[us,eu]"* || "$PR_TITLE" == *"[us,ap]"* ]]; then
            echo "us deployment required."
            echo "DEPLOY_us=true" >> $GITHUB_ENV
          else
            echo "us deployment not required. Skipping..."
            echo "DEPLOY_us=false" >> $GITHUB_ENV

      - name: Deploy us Region
        if: env.DEPLOY_us == 'true'
        run: |
          echo "Deploying us region..."
