name: Prod-EU Deployment

on:
  pull_request:
    branches:
      - prod  # Trigger only for PRs targeting 'prod' branch

jobs:
  deploy-eu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Parse PR Title for EU Deployment
        id: check_title
        run: |
          PR_TITLE=$(jq -r '.pull_request.title' < "$GITHUB_EVENT_PATH")
          echo "PR_TITLE=$PR_TITLE"

          if [[ "$PR_TITLE" =~ \[eu\] ]]; then
            echo "DEPLOY_EU=Y" >> $GITHUB_ENV
          else
            echo "DEPLOY_EU=N" >> $GITHUB_ENV
          fi

      - name: Deploy Prod-EU
        if: env.DEPLOY_EU == 'Y'
        run: |
          echo "Deploying Prod-EU region..."
          # Add your deployment commands for Prod-EU here

      - name: Skip EU Deployment
        if: env.DEPLOY_EU == 'N'
        run: |
          echo "No deployment for Prod-EU specified in PR title. Exiting."
          exit 0
