name: Prod-EU Deployment

on:
  pull_request:
    branches:
      - prod

jobs:
  deploy-eu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check if EU Deployment is Required
        id: check-eu
        run: |
          echo "Parsing PR title for EU region..."
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR Title: $PR_TITLE"

          if [[ "$PR_TITLE" == *"[eu]"* || "$PR_TITLE" == *"[ap,eu,us]"* || "$PR_TITLE" == *"[ap,eu]"* || "$PR_TITLE" == *"[eu,us]"* ]]; then
            echo "EU deployment required."
            echo "DEPLOY_EU=true" >> $GITHUB_ENV
          else
            echo "EU deployment not required. Skipping..."
            echo "DEPLOY_EU=false" >> $GITHUB_ENV

      - name: Deploy EU Region
        if: env.DEPLOY_EU == 'true'
        run: |
          echo "Deploying EU region..."
