name: Prod EU Deployment

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Parse PR Body
        id: parse_pr
        run: |
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")
          PROD_SELECTED=$(echo "$PR_BODY" | grep -oP '(?<=- Prod: `)[^`]+')
          PROD_IMAGE_EU=$(echo "$PR_BODY" | grep -A 3 "Prod Environment" | grep "EU Region:" | awk -F'`' '{print $2}' | tr -d '[:space:]')

          echo "PROD_SELECTED=$PROD_SELECTED" >> $GITHUB_ENV
          echo "PROD_IMAGE_EU=$PROD_IMAGE_EU" >> $GITHUB_ENV

      - name: Validate and Print Values
        run: |
          if [ "$PROD_SELECTED" == "Y" ]; then
            if [ -z "$PROD_IMAGE_EU" ]; then
              echo "Error: Missing image tag value for Prod EU Region."
              exit 1
            fi
            echo "Prod EU Region selected with image tag: $PROD_IMAGE_EU"
          else
            echo "Prod EU Region not selected. Skipping deployment."
