name: Prod-US Deployment

on:
  pull_request:
    branches:
      - prod


jobs:
  deploy-prod-us:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract PR Details
        run: |
          echo "Extracting PR details for Prod-US..."
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")

          # Check if Prod is selected
          PROD_SELECTED=$(echo "$PR_BODY" | grep -i "Prod: \`Y\`" || echo "")
          if [[ -z "$PROD_SELECTED" ]]; then
            echo "Prod environment not selected for deployment. Skipping..."
            exit 0
          fi

          # Extract US tag
          US_TAG=$(echo "$PR_BODY" | sed -n 's/.*\*\*US Region:\*\* `\([^`]*\)`/\1/p')
          if [[ -z "$US_TAG" ]]; then
            echo "US tag not provided for Prod. Exiting..."
            exit 1
          fi

          echo "US_TAG=$US_TAG" >> $GITHUB_ENV
          echo "Extracted US tag: $US_TAG"

      - name: Deploy to Prod US
        run: |
          echo "Deploying Prod US Region..."
          echo "Using US Tag: $US_TAG"
