name: Prod-EU Deployment

on:
  pull_request:
    branches:
      - prod  # Trigger only for PRs targeting 'prod' branch

jobs:
  deploy-eu:
    if: contains(github.event.pull_request.title, '[eu]')  # Trigger only if PR title contains '[eu]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Prod-EU
        run: |
          echo "Deploying Prod-EU region..."
          # Add your deployment commands for Prod-EU here
