name: Prod-EU Deployment

on:
  pull_request:
    branches:
      - prod

jobs:
  deploy-eu:
    if: contains(github.event.pull_request.title, '[eu]')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Image Tag Values
        id: extract-tags
        run: |
          echo "Extracting image tags for Prod-EU..."
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")

          # Extract the EU tag using sed
          EU_TAG=$(echo "$PR_BODY" | sed -n 's/.*### Prod Environment.*- \*\*EU Region:\*\* `\([^`]*\)`.*/\1/p')

          if [ -z "$EU_TAG" ]; then
            echo "EU tag not found or empty in the PR description!"
            exit 1
          fi

          echo "EU_TAG=$EU_TAG" >> $GITHUB_ENV
          echo "Extracted EU tag: $EU_TAG"

      - name: Deploy Prod-EU
        run: |
          echo "Deploying Prod-EU region..."
          echo "Using image tag: $EU_TAG"
