name: Prod-US Deployment
on:
  pull_request:
    branches:
      - prod

jobs:
  deploy-us:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check if US Deployment is Required
        id: check-us
        run: |
          echo "Parsing PR title for US region..."
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR Title: $PR_TITLE"

          if [[ "$PR_TITLE" == *"[us]"* || "$PR_TITLE" == *"[ap,eu,us]"* || "$PR_TITLE" == *"[eu,us]"* || "$PR_TITLE" == *"[ap,us]"* ]]; then
            echo "US deployment required."
            echo "DEPLOY_US=true" >> $GITHUB_ENV
          else
            echo "US deployment not required. Skipping..."
            echo "DEPLOY_US=false" >> $GITHUB_ENV

      - name: Deploy US Region
        if: env.DEPLOY_US == 'true'
        run: |
          echo "Deploying US region..."
