name: Prod - EU Region

on:
  pull_request:
    types: [opened, edited, reopened]
    paths:
      - .github/workflows/prod-eu.yaml

jobs:
  deploy-prod-eu:
    if: >
      github.event.pull_request.title contains 'ap' &&
      github.event.pull_request.title contains 'eu' &&
      github.event.pull_request.title contains 'us' &&
      github.event.pull_request.title contains 'rG'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Prod EU Deployment
        run: |
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")
          PROD_SELECTED=$(echo "$PR_BODY" | grep -oP '(?<=- Prod: `)[^`]+')

          if [ "$PROD_SELECTED" != "Y" ]; then
            echo "Prod environment not selected for deployment. Skipping."
            exit 0
          fi

          PROD_IMAGE_EU=$(echo "$PR_BODY" | grep -A 3 "Prod Environment" | grep "EU Region:" | awk -F'`' '{print $2}' | tr -d '[:space:]')
          if [ -z "$PROD_IMAGE_EU" ]; then
            echo "Error: Missing image tag for Prod EU Region."
            exit 1
          fi

          echo "Deploying Prod - EU Region with image tag: $PROD_IMAGE_EU"
