name: Staging US Deployment

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Parse PR Body
        id: parse_pr
        run: |
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")
          STAGING_SELECTED=$(echo "$PR_BODY" | grep -oP '(?<=- Staging: `)[^`]+')
          STAGING_IMAGE_US=$(echo "$PR_BODY" | grep -A 3 "Staging Environment" | grep "US Region:" | awk -F'`' '{print $2}' | tr -d '[:space:]')

          echo "STAGING_SELECTED=$STAGING_SELECTED" >> $GITHUB_ENV
          echo "STAGING_IMAGE_US=$STAGING_IMAGE_US" >> $GITHUB_ENV

      - name: Validate and Print Values
        run: |
          if [ "$STAGING_SELECTED" == "Y" ]; then
            if [ -z "$STAGING_IMAGE_US" ]; then
              echo "Error: Missing image tag value for Staging US Region."
              exit 1
            fi
            echo "Staging US Region selected with image tag: $STAGING_IMAGE_US"
          else
            echo "Staging US Region not selected. Skipping deployment."
