name: Staging-AP Deployment

on:
  pull_request:
    branches:
      - staging

jobs:
  deploy-staging-ap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract PR Details
        run: |
          echo "Extracting PR details for Staging-AP..."
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")

          # Check if Staging is selected
          STAGING_SELECTED=$(echo "$PR_BODY" | grep -i "Staging: \`Y\`" || echo "")
          if [[ -z "$STAGING_SELECTED" ]]; then
            echo "Staging environment not selected for deployment. Skipping..."
            exit 0
          fi

          # Extract AP tag using sed
          AP_TAG=$(echo "$PR_BODY" | sed -n 's/.*\*\*AP Region:\*\* `\([^`]*\)`/\1/p')
          if [[ -z "$AP_TAG" ]]; then
            echo "AP tag not provided for Staging. Exiting..."
            exit 1
          fi

          echo "AP_TAG=$AP_TAG" >> $GITHUB_ENV
          echo "Extracted AP tag: $AP_TAG"

      - name: Deploy to Staging AP
        run: |
          echo "Deploying Staging AP Region..."
          echo "Using AP Tag: $AP_TAG"
