name: Deploy to Staging - EU Region

on:
  pull_request:
    branches:
      - staging

jobs:
  deploy-staging-eu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Deploy to Staging - EU
        run: |
          echo "Deploying to Staging EU Region with Image Tag: ${{ secrets.STAGING_EU_IMAGE_TAG }}"
