name: Deploy to Staging - AP Region

on:
  pull_request:
    branches:
      - staging

jobs:
  deploy-staging-ap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract image tag for Staging AP
        run: |
          PR_BODY=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }})
          
          IMAGE_TAG_STAGING_AP=$(echo "$PR_BODY" | grep -oP '(?<=Staging: )[^\n]+' | xargs)
          echo "Staging AP Image Tag: $IMAGE_TAG_STAGING_AP"
          echo "IMAGE_TAG_STAGING_AP=$IMAGE_TAG_STAGING_AP" >> $GITHUB_ENV

      - name: Deploy to Staging - AP
        run: |
          echo "Deploying to Staging AP Region with Image Tag: $IMAGE_TAG_STAGING_AP"
          # Add your deployment command here, e.g., kubectl, docker, etc.
