name: Staging-EU Deployment

on:
  pull_request:
    branches:
      - staging

jobs:
  deploy-staging-eu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract PR Details
        run: |
          echo "Extracting PR details for Staging-EU..."
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")

          STAGING_SELECTED=$(echo "$PR_BODY" | grep -i "Staging: \`Y\`" || echo "")
          if [[ -z "$STAGING_SELECTED" ]]; then
            echo "Staging environment not selected for deployment. Skipping..."
            exit 0
          fi

          EU_TAG=$(echo "$PR_BODY" | sed -n 's/.*\*\*EU Region:\*\* `\([^`]*\)`/\1/p')
          if [[ -z "$EU_TAG" ]]; then
            echo "EU tag not provided for Staging. Exiting..."
            exit 1
          fi

          echo "EU_TAG=$EU_TAG" >> $GITHUB_ENV
          echo "Extracted EU tag: $EU_TAG"

      - name: Deploy to Staging EU
        run: |
          echo "Deploying Staging EU Region..."
          echo "Using EU Tag: $EU_TAG"
