name: Staging-US Deployment
on:
  pull_request:
    branches:
      - staging

jobs:
  deploy-staging-us:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract PR Details
        run: |
          echo "Extracting PR details for Staging-US..."
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")

          # Check if Staging is selected
          STAGING_SELECTED=$(echo "$PR_BODY" | grep -i "Staging: \`Y\`" || echo "")
          if [[ -z "$STAGING_SELECTED" ]]; then
            echo "Staging environment not selected for deployment. Skipping..."
            exit 0
          fi

          # Extract US tag
          US_TAG=$(echo "$PR_BODY" | sed -n 's/.*\*\*US Region:\*\* `\([^`]*\)`/\1/p')
          if [[ -z "$US_TAG" ]]; then
            echo "US tag not provided for Staging. Exiting..."
            exit 1
          fi

          echo "US_TAG=$US_TAG" >> $GITHUB_ENV
          echo "Extracted US tag: $US_TAG"

      - name: Deploy to Staging US
        run: |
          echo "Deploying Staging US Region..."
          echo "Using US Tag: $US_TAG"
