name: Staging EU Deployment

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Parse PR Body
        id: parse_pr
        run: |
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")
          STAGING_SELECTED=$(echo "$PR_BODY" | grep -oP '(?<=- Staging: `)[^`]+')
          STAGING_IMAGE_EU=$(echo "$PR_BODY" | grep -A 3 "Staging Environment" | grep "EU Region:" | awk -F'`' '{print $2}' | tr -d '[:space:]')

          echo "STAGING_SELECTED=$STAGING_SELECTED" >> $GITHUB_ENV
          echo "STAGING_IMAGE_EU=$STAGING_IMAGE_EU" >> $GITHUB_ENV

      - name: Validate and Print Values
        run: |
          if [ "$STAGING_SELECTED" == "Y" ]; then
            if [ -z "$STAGING_IMAGE_EU" ]; then
              echo "Error: Missing image tag value for Staging EU Region."
              exit 1
            fi
            echo "Staging EU Region selected with image tag: $STAGING_IMAGE_EU"
          else
            echo "Staging EU Region not selected. Skipping deployment."
